version: '3.3'
services:
    app:
      build: ./
      container_name: app
      command: bash -c ". venv/bin/activate
              && python main.py"
      restart: always
      ports:
        - 8000:8000